[package]
name = "cargo-diet"
version = "0.1.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
failure = "0.1.1"
failure-tools = "4.0.2"
structopt = "0.3.14"

[[bin]]
name="cargo-diet"
path="src/main.rs"

[profile.release]
panic = 'unwind'
incremental = false
overflow-checks = true
