[package]
name = "cargo-diet"
version = "1.0.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
structopt = "0.3.14"
anyhow = "1.0.31"
quick-error = "1.2.3"
locate-cargo-manifest = "0.2.0"

[[bin]]
name="cargo-diet"
path="src/main.rs"

[profile.release]
panic = 'unwind'
incremental = false
overflow-checks = true
