[package]
name = "cargo-diet"
version = "0.1.0"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
description = "A cargo-companion to compute exclude and include directives"
publish = false
include = ["src/**/*", "Cargo.*", "README.md", "LICENSE.md"]
license = "MIT"
repository = "https://github.com/crates-io/cargo-diet"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
