name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make journey-tests
    - name: Check crate package size
      run: cargo run -- diet --dry-run --package-size-limit 10KB
    - name: fmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy
